---
title: "Data Import"
output: github_document
---

## Data Import: CSVs


```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

```{r}
litters_df = read.csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

##to clean the name of the data frame##
```

```{r}
litters_df

head(litters_df)

##to check the head and tails of a data table##
```

```{r, eval=FALSE}

view(litters_df)

##using eval=false to prevent troubles when knitting##
```

```{r}
skimr::skim(litters_df)

##quick summary of the entire data set##
```

'read_csv' options..
```{r}
read_csv("data/FAS_litters.csv", na = c("", "NA", 88), skip = 2)
```

## Other file formats

We need to read an excel spread sheet

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r, eval=FALSE}
view(mlb_df)
```

```{r}
lotr_words_df = 
  read_excel(
    "data/LotR_Words.xlsx",
    range = "B3:D6")
lotr_words_df
```

## Still more formats

Read in SAS dataset

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

##Data export

```{r}
write_csv(lotr_words_df, file = "data/lotr_words_df.csv")
```

## never use "read.csv" as it transfers character varaible to categorical##




